### ISSUE TITLE
SBE fails to install images

### ISSUE THREAD

**Issue by madscientist159** [open-power/sbe#6]
Commit d43ff15ada7dd3cb313de3aa91a3996b2ef06a69 deleted the definition of SEEPROM_IMAGE, but SEEPROM_IMAGE is  still referenced in src/build/sbeOpDistribute.py.

Result:
```
t > op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/images/sbe_seeprom_DD2.rpt
make[2]: Leaving directory 'op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/src/build'
make[1]: Leaving directory 'op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8'
>>> sbe 9b03db45c424d6edc5698fa74830dc1d432fdfe8 Installing to images directory
/usr/bin/install -D op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/images/p9_ipl_build  op-build/output/host/usr/bin/
python op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/src/build/sbeOpDistribute.py --sbe_binary_dir=op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/sbe_binaries --img_dir=op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/images
Cmd:<mkdir -p op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/sbe_binaries>
Traceback (most recent call last):
  File "op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/src/build/sbeOpDistribute.py", line 114, in <module>
    main(sys.argv)
  File "op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/src/build/sbeOpDistribute.py", line 94, in main
    run_system_cmd('cp '+img_dir+'/'+'sbe_seeprom_'+ddLevel+'.bin'+' '+sbe_binary_dir+'/'+CHIPID+'_'+ecLevel+'.'+SEEPROM_IMAGE)
NameError: global name 'SEEPROM_IMAGE' is not defined
package/pkg-generic.mk:305: recipe for target 'op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/.stamp_images_installed' failed
make: *** [op-build/output/build/sbe-9b03db45c424d6edc5698fa74830dc1d432fdfe8/.stamp_images_installed] Error 1
make: Leaving directory 'op-build/buildroot'
```

**Comment by sgupta2m** [comment]
Fixed.

**Comment by madscientist159** [comment]
Thanks!  Looks like the same fix [we had used in our tree](https://git.raptorcs.com/git/talos-sbe/commit/?id=65f6ced5f9577ed20549b490bfc1a0ebd28926c0)
